CREATE TABLE IF NOT EXISTS TRANSFERENCIA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    REQUEST_ID TEXT NOT NULL UNIQUE,
    CONTA_DESTINO TEXT NOT NULL,
    VALOR NUMERIC NOT NULL,
    STATUS TEXT NOT NULL,
    DATA_HORA TEXT NOT NULL
);
