CREATE TABLE IF NOT EXISTS CONTACORRENTE (
    ID TEXT PRIMARY KEY,
    NUMERO_CONTA TEXT NOT NULL UNIQUE,
    NOME_TITULAR TEXT NOT NULL,
    CPF TEXT NOT NULL UNIQUE,
    SENHA_HASH TEXT NOT NULL,
    ATIVO INTEGER NOT NULL,
    DATA_CRIACAO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MOVIMENTO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    REQUEST_ID TEXT NOT NULL,
    NUMERO_CONTA TEXT NOT NULL,
    VALOR NUMERIC NOT NULL,
    TIPO TEXT NOT NULL,
    DATA_HORA TEXT NOT NULL,
    UNIQUE (REQUEST_ID, NUMERO_CONTA)
);

CREATE INDEX IF NOT EXISTS IX_MOVIMENTO_CONTA
ON MOVIMENTO (NUMERO_CONTA);
